/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/action-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Action Kinds
         * @description 首屏的场景引子来源。
         *
         *     新增一个行动类别时首屏自动多一张卡，前端不改代码——这是扩展点的
         *     可见证据。
         */
        get: operations["list_action_kinds_api_action_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents:compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Intent
         * @description 把一句话整理成可检查的结构。**不写库。**
         */
        post: operations["compile_intent_api_intents_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Intent
         * @description 保存用户校对后的意图。
         *
         *     `stash=true` 存成念头：只对本人可见、不参与撮合、无过期压力。
         *     否则存成草稿，等用户确认。两者都还不能被撮合到。
         */
        post: operations["create_intent_api_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intent */
        get: operations["get_intent_api_intents__intent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Revise Intent
         * @description 改内容。改完回到草稿——旧的确认不能沿用到新内容上。
         */
        patch: operations["revise_intent_api_intents__intent_id__patch"];
        trace?: never;
    };
    "/api/intents/{intent_id}:confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Intent
         * @description 用户确认结构化结果无误。这是"未经确认不得进入撮合"的那道门。
         */
        post: operations["confirm_intent_api_intents__intent_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}:withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw Intent */
        post: operations["withdraw_intent_api_intents__intent_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Intents
         * @description 本人的全部意图，含念头。
         *
         *     念头只出现在这里——系统里没有任何端点会返回**别人的**念头。
         */
        get: operations["list_my_intents_api_me_intents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description 还能报名的招募。已满和已过期的不出现——列表上每一条都该能点。
         */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        /**
         * Create Opportunity
         * @description 发布招募。发布者即负责人——没有负责人的成局会导致责任分散。
         */
        post: operations["create_opportunity_api_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{organization_id}/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List For Organization
         * @description 组织者侧：含已满与已关闭的，他们要看全貌才知道要不要补推。
         */
        get: operations["list_for_organization_api_organizations__organization_id__opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}/grantable-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grantable Fields
         * @description 这次可以逐项授权的字段。
         *
         *     空字段也列出来但标 `present=false`——界面据此把它们灰掉，
         *     而不是让用户对着一个没内容的开关犹豫。
         */
        get: operations["grantable_fields_api_intents__intent_id__grantable_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}/envelope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Envelope
         * @description 保存这次的授权，并留下一条同意记录。
         *
         *     信封会被撤销和过期；同意记录只追加不修改——申诉和导出看的是后者。
         */
        put: operations["put_envelope_api_intents__intent_id__envelope_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/envelopes/{envelope_id}:revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Envelope
         * @description 收回授权。撤销后新请求立刻被拒，不用等任何异步清理。
         */
        post: operations["revoke_envelope_api_envelopes__envelope_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Grants
         * @description 「谁能看到我」。仍在生效的授权，可一键收回。
         */
        get: operations["my_grants_api_me_grants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview
         * @description 别人在小队说明里会看到我的什么。
         *
         *     投影按信封求出的可见字段集合做——和真正对外输出走的是同一条路径，
         *     所以这一屏显示什么，对方就真的只看到什么。
         */
        get: operations["preview_api_intents__intent_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/stash-hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stash Hints
         * @description 我记下的念头，以及现在有哪些招募对得上。
         *
         *     出现在本人的入口页，不产生推送。
         */
        get: operations["stash_hints_api_me_stash_hints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/waiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waiting */
        get: operations["waiting_api_me_waiting_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clearing:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Clearing
         * @description 把到点的市场单元结算一次。
         *
         *     它存在是为了让**推进时钟就能看到配队发生**——演示不需要真等六小时。
         *     重复调用是安全的：同一个窗口内幂等。
         */
        post: operations["run_clearing_api_clearing_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Teams For
         * @description 这条需求配到的小队。
         *
         *     只给 2–3 个。实证表明选择变多反而降低决策质量——搜索上限 3→100 时
         *     福利显著下降。多给几个不是慷慨，是把决策成本转嫁给用户。
         */
        get: operations["teams_for_api_intents__intent_id__teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blocked For
         * @description 凑不出队时说什么。
         *
         *     这一屏最容易被做成一句"暂无结果"，而那正是用户流失的地方。
         */
        get: operations["blocked_for_api_intents__intent_id__blocked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gate Status */
        get: operations["gate_status_api_proposals__proposal_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}:invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite
         * @description 给这一版条款的每个成员开一条待答复。重复调用不重置任何人的答复。
         */
        post: operations["invite_api_proposals__proposal_id__invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}:decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description 一个真人做出决定。
         *
         *     **身份取自请求头，不取自请求体**——请求体里带 principal_id
         *     等于任何人都能替任何人承诺，而承诺只接受真人签名的命令。
         */
        post: operations["decide_api_proposals__proposal_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionKindOut */
        ActionKindOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            starter: components["schemas"]["StarterOut"];
            /** Risk Tier */
            risk_tier: string;
            /** Place Precision */
            place_precision: string;
            /** Agent Reply Policy */
            agent_reply_policy: string;
            /** Matching Window Seconds */
            matching_window_seconds: number;
        };
        /**
         * BlockedOut
         * @description 「还差这几件事」那一屏。凑不出队时把挫败换成一个具体的下一步。
         */
        BlockedOut: {
            /** Stage */
            stage: string;
            /** Statement */
            statement: string;
            /** Causes */
            causes: string[];
            /** Relaxations */
            relaxations: components["schemas"]["RelaxationOut"][];
            /** Next Steps */
            next_steps: components["schemas"]["NextStepOut"][];
        };
        /** ClearingOut */
        ClearingOut: {
            /** Considered */
            considered: number;
            /** Proposed */
            proposed: number;
            /** Blocked */
            blocked: number;
            /** Early */
            early: number;
        };
        /** CompileRequest */
        CompileRequest: {
            /** Expression */
            expression: string;
        };
        /**
         * CompileResponse
         * @description 抽取结果。**它只是草稿**——没有用户确认，什么都进不了撮合。
         */
        CompileResponse: {
            content: components["schemas"]["IntentContentOut"];
            /**
             * Follow Ups
             * @default []
             */
            follow_ups: components["schemas"]["FollowUpOut"][];
            /**
             * Conflicts
             * @default []
             */
            conflicts: components["schemas"]["ConflictOut"][];
            /** Confidence */
            confidence: number;
            /** Fall Back To Form */
            fall_back_to_form: boolean;
        };
        /**
         * ConflictOut
         * @description 指出是哪两条约束打架，不泛泛说"输入有误"。
         */
        ConflictOut: {
            /** Field */
            field: string;
            /** Detail */
            detail: string;
        };
        /** CreateIntentRequest */
        CreateIntentRequest: {
            /** Expression */
            expression: string;
            content: components["schemas"]["IntentContentIn"];
            /** Action Kind */
            action_kind?: string | null;
            /**
             * Stash
             * @default false
             */
            stash: boolean;
        };
        /** CreateOpportunityRequest */
        CreateOpportunityRequest: {
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Kind Key */
            kind_key: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            /** Seats */
            seats: components["schemas"]["SeatIn"][];
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Location Scope */
            location_scope?: string | null;
            /**
             * Qualifications
             * @default []
             */
            qualifications: string[];
        };
        /** DecideRequest */
        DecideRequest: {
            /** Answer */
            answer: string;
            /** Condition */
            condition?: string | null;
        };
        /** EnvelopeOut */
        EnvelopeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /** Grants */
            grants: components["schemas"]["GrantOut"][];
            /** Cited Facet Ids */
            cited_facet_ids: string[];
            /** State */
            state: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Consent Record Id */
            consent_record_id?: string | null;
        };
        /** FollowUpOut */
        FollowUpOut: {
            /** Text */
            text: string;
            /** Narrows */
            narrows: string;
            /**
             * Options
             * @default []
             */
            options: string[];
        };
        /**
         * GapOut
         * @description 一样本事：多少人要、多少人给得出。只给聚合数，不给名字。
         */
        GapOut: {
            /** Skill */
            skill: string;
            /** Wanted */
            wanted: number;
            /** Offered */
            offered: number;
            /** Scarce */
            scarce: boolean;
        };
        /**
         * GateStatusOut
         * @description 还在等谁。**已决的折叠起来，这里只出未决的。**
         */
        GateStatusOut: {
            /** Verdict */
            verdict: string;
            /** Waiting On */
            waiting_on?: string[];
            /** Conditions */
            conditions?: string[];
            /** Formed Event Id */
            formed_event_id?: string | null;
            /** Space Id */
            space_id?: string | null;
        };
        /** GrantIn */
        GrantIn: {
            /** Field Name */
            field_name: string;
            /**
             * Audience
             * @default solver_only
             */
            audience: string;
        };
        /** GrantOut */
        GrantOut: {
            /** Field Name */
            field_name: string;
            /** Audience */
            audience: string;
            /** Purposes */
            purposes: string[];
            /** Purpose Label */
            purpose_label: string;
        };
        /** GrantableFieldOut */
        GrantableFieldOut: {
            /** Field Name */
            field_name: string;
            /** Label */
            label: string;
            /** Present */
            present: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HintOut */
        HintOut: {
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /** Title */
            title: string;
            /** Organization Name */
            organization_name: string;
            /** Organization Verified */
            organization_verified: boolean;
            /** Because */
            because: string;
            /** Total Gap */
            total_gap: number;
        };
        /**
         * IntentContentIn
         * @description 用户校对后回传的内容。抽取给的是草稿，这才是权威。
         */
        IntentContentIn: {
            /** Goal */
            goal: string;
            /**
             * Offers
             * @default []
             */
            offers: string[];
            /**
             * Needs
             * @default []
             */
            needs: string[];
            time_window?: components["schemas"]["TimeWindowOut"] | null;
            /** Location Scope */
            location_scope?: string | null;
            team_size?: components["schemas"]["TeamSizeOut"] | null;
            /**
             * Boundaries
             * @default []
             */
            boundaries: string[];
            /**
             * Open Questions
             * @default []
             */
            open_questions: string[];
        };
        /** IntentContentOut */
        IntentContentOut: {
            /** Goal */
            goal: string;
            /**
             * Offers
             * @default []
             */
            offers: string[];
            /**
             * Needs
             * @default []
             */
            needs: string[];
            time_window?: components["schemas"]["TimeWindowOut"] | null;
            /** Location Scope */
            location_scope?: string | null;
            team_size?: components["schemas"]["TeamSizeOut"] | null;
            /**
             * Boundaries
             * @default []
             */
            boundaries: string[];
            /**
             * Open Questions
             * @default []
             */
            open_questions: string[];
            /**
             * Uncertain Fields
             * @default []
             */
            uncertain_fields: string[];
        };
        /** IntentOut */
        IntentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /** State */
            state: string;
            /** Raw Expression */
            raw_expression: string;
            content: components["schemas"]["IntentContentOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Is Matchable */
            is_matchable: boolean;
            /** Action Kind */
            action_kind?: string | null;
        };
        /** NextStepOut */
        NextStepOut: {
            /** Kind */
            kind: string;
            /** Invitation */
            invitation: string;
        };
        /** OpportunityOut */
        OpportunityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            /** Organization Verified */
            organization_verified: boolean;
            /** Kind Key */
            kind_key: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            /** Seats */
            seats: components["schemas"]["SeatOut"][];
            /** Total Gap */
            total_gap: number;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Location Scope */
            location_scope: string | null;
            /** Qualifications */
            qualifications: string[];
            /** State */
            state: string;
        };
        /**
         * PreviewOut
         * @description 「别人眼中的我」。
         *
         *     这一屏让"最小披露"从一句承诺变成用户可以自己检查的东西。
         */
        PreviewOut: {
            /** Visible */
            visible: {
                [key: string]: unknown;
            };
            /** Withheld */
            withheld: string[];
        };
        /** ProofLineOut */
        ProofLineOut: {
            /** Text */
            text: string;
            /** Source */
            source: string;
        };
        /** PutEnvelopeRequest */
        PutEnvelopeRequest: {
            /** Grants */
            grants?: components["schemas"]["GrantIn"][];
            /** Cited Facet Ids */
            cited_facet_ids?: string[];
        };
        /** RelaxationOut */
        RelaxationOut: {
            /** Field Name */
            field_name: string;
            /** Invitation */
            invitation: string;
            /** Gains */
            gains: number;
            /** Advisable */
            advisable: boolean;
            /**
             * Caution
             * @default
             */
            caution: string;
        };
        /** ReviseIntentRequest */
        ReviseIntentRequest: {
            content: components["schemas"]["IntentContentIn"];
        };
        /** SeatIn */
        SeatIn: {
            /** Role */
            role: string;
            /** Capacity */
            capacity: number;
        };
        /** SeatOut */
        SeatOut: {
            /** Role */
            role: string;
            /** Capacity */
            capacity: number;
            /** Filled */
            filled: number;
            /** Gap */
            gap: number;
        };
        /** StarterOut */
        StarterOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Example */
            example: string;
            /**
             * Roles
             * @default []
             */
            roles: string[];
        };
        /** StashHintOut */
        StashHintOut: {
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /** Note */
            note: string;
            /** Hints */
            hints: components["schemas"]["HintOut"][];
        };
        /** TeamMemberOut */
        TeamMemberOut: {
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * TeamOut
         * @description 一个小队。**没有分数，没有百分比**——理由是逐条的。
         */
        TeamOut: {
            /**
             * Proposal Id
             * Format: uuid
             */
            proposal_id: string;
            /** Members */
            members: components["schemas"]["TeamMemberOut"][];
            /** Why These People */
            why_these_people: components["schemas"]["ProofLineOut"][];
            /** Left To Humans */
            left_to_humans: components["schemas"]["ProofLineOut"][];
            /** Uncertainties */
            uncertainties: components["schemas"]["ProofLineOut"][];
            /** Stability Note */
            stability_note?: string | null;
            /** Expires At */
            expires_at: string;
        };
        /** TeamSizeOut */
        TeamSizeOut: {
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** TimeWindowOut */
        TimeWindowOut: {
            /**
             * Earliest
             * Format: date-time
             */
            earliest: string;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WaitingOut
         * @description 「等配队」那一屏。
         *
         *     光说"请稍候"用户只会走掉；说"现在 12 个人缺剪辑，只有 3 个人会"，
         *     他就知道该改需求、该去拉人、还是该自己顶上。
         */
        WaitingOut: {
            /** Next Round At */
            next_round_at: string;
            /** Waiting Count */
            waiting_count: number;
            /** Gaps */
            gaps: components["schemas"]["GapOut"][];
            /**
             * Can Still Revise
             * @default true
             */
            can_still_revise: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_action_kinds_api_action_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionKindOut"][];
                };
            };
        };
    };
    compile_intent_api_intents_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intent_api_intents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intent_api_intents__intent_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_intent_api_intents__intent_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_intent_api_intents__intent_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_intent_api_intents__intent_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_intents_api_me_intents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_api_opportunities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_for_organization_api_organizations__organization_id__opportunities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grantable_fields_api_intents__intent_id__grantable_fields_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantableFieldOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_envelope_api_intents__intent_id__envelope_put: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutEnvelopeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_envelope_api_envelopes__envelope_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path: {
                envelope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_grants_api_me_grants_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvelopeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_intents__intent_id__preview_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stash_hints_api_me_stash_hints_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashHintOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waiting_api_me_waiting_get: {
        parameters: {
            query?: {
                action_kind?: string | null;
            };
            header?: {
                "x-campus-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_clearing_api_clearing_run_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teams_for_api_intents__intent_id__teams_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    blocked_for_api_intents__intent_id__blocked_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gate_status_api_proposals__proposal_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_api_proposals__proposal_id__invite_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_proposals__proposal_id__decide_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
