/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/action-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Action Kinds
         * @description 首屏的场景引子来源。
         *
         *     新增一个行动类别时首屏自动多一张卡，前端不改代码——这是扩展点的
         *     可见证据。
         */
        get: operations["list_action_kinds_api_action_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents:compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Intent
         * @description 把一句话整理成可检查的结构。**不写库。**
         */
        post: operations["compile_intent_api_intents_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Intent
         * @description 保存用户校对后的意图。
         *
         *     `stash=true` 存成念头：只对本人可见、不参与撮合、无过期压力。
         *     否则存成草稿，等用户确认。两者都还不能被撮合到。
         */
        post: operations["create_intent_api_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intent */
        get: operations["get_intent_api_intents__intent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Revise Intent
         * @description 改内容。改完回到草稿——旧的确认不能沿用到新内容上。
         */
        patch: operations["revise_intent_api_intents__intent_id__patch"];
        trace?: never;
    };
    "/api/intents/{intent_id}:confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Intent
         * @description 用户确认结构化结果无误。这是"未经确认不得进入撮合"的那道门。
         */
        post: operations["confirm_intent_api_intents__intent_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intents/{intent_id}:withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw Intent */
        post: operations["withdraw_intent_api_intents__intent_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Intents
         * @description 本人的全部意图，含念头。
         *
         *     念头只出现在这里——系统里没有任何端点会返回**别人的**念头。
         */
        get: operations["list_my_intents_api_me_intents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description 还能报名的招募。已满和已过期的不出现——列表上每一条都该能点。
         */
        get: operations["list_opportunities_api_opportunities_get"];
        put?: never;
        /**
         * Create Opportunity
         * @description 发布招募。发布者即负责人——没有负责人的成局会导致责任分散。
         */
        post: operations["create_opportunity_api_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{organization_id}/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List For Organization
         * @description 组织者侧：含已满与已关闭的，他们要看全貌才知道要不要补推。
         */
        get: operations["list_for_organization_api_organizations__organization_id__opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionKindOut */
        ActionKindOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            starter: components["schemas"]["StarterOut"];
            /** Risk Tier */
            risk_tier: string;
            /** Place Precision */
            place_precision: string;
            /** Agent Reply Policy */
            agent_reply_policy: string;
            /** Matching Window Seconds */
            matching_window_seconds: number;
        };
        /** CompileRequest */
        CompileRequest: {
            /** Expression */
            expression: string;
        };
        /**
         * CompileResponse
         * @description 抽取结果。**它只是草稿**——没有用户确认，什么都进不了撮合。
         */
        CompileResponse: {
            content: components["schemas"]["IntentContentOut"];
            /**
             * Follow Ups
             * @default []
             */
            follow_ups: components["schemas"]["FollowUpOut"][];
            /**
             * Conflicts
             * @default []
             */
            conflicts: components["schemas"]["ConflictOut"][];
            /** Confidence */
            confidence: number;
            /** Fall Back To Form */
            fall_back_to_form: boolean;
        };
        /**
         * ConflictOut
         * @description 指出是哪两条约束打架，不泛泛说"输入有误"。
         */
        ConflictOut: {
            /** Field */
            field: string;
            /** Detail */
            detail: string;
        };
        /** CreateIntentRequest */
        CreateIntentRequest: {
            /** Expression */
            expression: string;
            content: components["schemas"]["IntentContentIn"];
            /**
             * Stash
             * @default false
             */
            stash: boolean;
        };
        /** CreateOpportunityRequest */
        CreateOpportunityRequest: {
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Kind Key */
            kind_key: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            /** Seats */
            seats: components["schemas"]["SeatIn"][];
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Location Scope */
            location_scope?: string | null;
            /**
             * Qualifications
             * @default []
             */
            qualifications: string[];
        };
        /** FollowUpOut */
        FollowUpOut: {
            /** Text */
            text: string;
            /** Narrows */
            narrows: string;
            /**
             * Options
             * @default []
             */
            options: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntentContentIn
         * @description 用户校对后回传的内容。抽取给的是草稿，这才是权威。
         */
        IntentContentIn: {
            /** Goal */
            goal: string;
            /**
             * Offers
             * @default []
             */
            offers: string[];
            /**
             * Needs
             * @default []
             */
            needs: string[];
            time_window?: components["schemas"]["TimeWindowOut"] | null;
            /** Location Scope */
            location_scope?: string | null;
            team_size?: components["schemas"]["TeamSizeOut"] | null;
            /**
             * Boundaries
             * @default []
             */
            boundaries: string[];
            /**
             * Open Questions
             * @default []
             */
            open_questions: string[];
        };
        /** IntentContentOut */
        IntentContentOut: {
            /** Goal */
            goal: string;
            /**
             * Offers
             * @default []
             */
            offers: string[];
            /**
             * Needs
             * @default []
             */
            needs: string[];
            time_window?: components["schemas"]["TimeWindowOut"] | null;
            /** Location Scope */
            location_scope?: string | null;
            team_size?: components["schemas"]["TeamSizeOut"] | null;
            /**
             * Boundaries
             * @default []
             */
            boundaries: string[];
            /**
             * Open Questions
             * @default []
             */
            open_questions: string[];
            /**
             * Uncertain Fields
             * @default []
             */
            uncertain_fields: string[];
        };
        /** IntentOut */
        IntentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Principal Id
             * Format: uuid
             */
            principal_id: string;
            /** State */
            state: string;
            /** Raw Expression */
            raw_expression: string;
            content: components["schemas"]["IntentContentOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Is Matchable */
            is_matchable: boolean;
        };
        /** OpportunityOut */
        OpportunityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            /** Organization Verified */
            organization_verified: boolean;
            /** Kind Key */
            kind_key: string;
            /** Title */
            title: string;
            /** Goal */
            goal: string;
            /** Seats */
            seats: components["schemas"]["SeatOut"][];
            /** Total Gap */
            total_gap: number;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
            /** Location Scope */
            location_scope: string | null;
            /** Qualifications */
            qualifications: string[];
            /** State */
            state: string;
        };
        /** ReviseIntentRequest */
        ReviseIntentRequest: {
            content: components["schemas"]["IntentContentIn"];
        };
        /** SeatIn */
        SeatIn: {
            /** Role */
            role: string;
            /** Capacity */
            capacity: number;
        };
        /** SeatOut */
        SeatOut: {
            /** Role */
            role: string;
            /** Capacity */
            capacity: number;
            /** Filled */
            filled: number;
            /** Gap */
            gap: number;
        };
        /** StarterOut */
        StarterOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Example */
            example: string;
            /**
             * Roles
             * @default []
             */
            roles: string[];
        };
        /** TeamSizeOut */
        TeamSizeOut: {
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** TimeWindowOut */
        TimeWindowOut: {
            /**
             * Earliest
             * Format: date-time
             */
            earliest: string;
            /**
             * Deadline
             * Format: date-time
             */
            deadline: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_action_kinds_api_action_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionKindOut"][];
                };
            };
        };
    };
    compile_intent_api_intents_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intent_api_intents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intent_api_intents__intent_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_intent_api_intents__intent_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_intent_api_intents__intent_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_intent_api_intents__intent_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_intents_api_me_intents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_api_opportunities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_api_opportunities_post: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
                "x-principal-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_for_organization_api_organizations__organization_id__opportunities_get: {
        parameters: {
            query?: never;
            header?: {
                "x-campus-id"?: string | null;
            };
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
